In [13]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os 
import shutil

In [14]:
initial_df = pd.read_csv('dataframe_wave3_subjects.csv')
initial_df.head()

,Subject_ID,imaging waves,SWS-waves,ADHD,ChildGender,ID_number,d1_diagadhd_dich,d3_diaagadhd_dich,d5_diagadhd_dich,p0_cpadhdi_raw,p3_cpadhdi_raw,p4_cpadhdi_raw,p5_cpadhdi_raw,d3_ad_inattcri_y,d3_ad_hypcri_y
0,sub-0015,"1,2,3","4,5",0,1,15,0.0,0,0.0,0,0.0,0.0,0.0,0,0
1,sub-0071,1,4,1,1,71,1.0,1,NaN,14,12.0,12.0,NaN,7,5
2,sub-0085,"2,3","4,5",0,0,85,0.0,0,0.0,5,14.0,0.0,1.0,5,0
3,sub-0086,"1,2,3",NaN,0,1,86,1.0,1,0.0,16,11.0,18.0,NaN,7,5
4,sub-0134,"1,3","4,5",0,1,134,0.0,0,0.0,2,0.0,0.0,0.0,0,0

In [15]:
group_bold = pd.read_csv('group_bold.tsv', sep='\t')
fd_mean = group_bold["fd_mean"]

In [17]:
df = pd.DataFrame(columns=initial_df.columns)
initialdf = initial_df

### spliting imaging waves

In [18]:
initialdf["imaging waves"] = initialdf["imaging waves"].str.split(",")
initialdf["SWS-waves"] = initialdf["SWS-waves"].str.split(",")
initialdf.head()

,Subject_ID,imaging waves,SWS-waves,ADHD,ChildGender,ID_number,d1_diagadhd_dich,d3_diaagadhd_dich,d5_diagadhd_dich,p0_cpadhdi_raw,p3_cpadhdi_raw,p4_cpadhdi_raw,p5_cpadhdi_raw,d3_ad_inattcri_y,d3_ad_hypcri_y
0,sub-0015,"[1, 2, 3]","[4, 5]",0,1,15,0.0,0,0.0,0,0.0,0.0,0.0,0,0
1,sub-0071,[1],[4],1,1,71,1.0,1,NaN,14,12.0,12.0,NaN,7,5
2,sub-0085,"[2, 3]","[4, 5]",0,0,85,0.0,0,0.0,5,14.0,0.0,1.0,5,0
3,sub-0086,"[1, 2, 3]",NaN,0,1,86,1.0,1,0.0,16,11.0,18.0,NaN,7,5
4,sub-0134,"[1, 3]","[4, 5]",0,1,134,0.0,0,0.0,2,0.0,0.0,0.0,0,0

### deleting swsless

In [19]:
initialdf = initialdf.dropna(axis=0, subset=['SWS-waves'])
index = initialdf['Subject_ID']
initialdf = initialdf.set_index('Subject_ID')

In [20]:
for i in index:
    a = initialdf.loc[[i]]
    s = a['imaging waves']
    sws = a['SWS-waves'][0]
    a = a.reset_index()
    for j in range(len(s[0])):
        if s[0][j] == '1':
            continue
        if s[0][j] == '2':
            continue
        
        try:
            if int(sws[0])-2 == int(s[0][j]):
                a['SWS-waves']=1
            elif int(sws[1])-2 == int(s[0][j]):
                a['SWS-waves']=1
            else:
                a['SWS-waves']=0
        except:
            a['SWS-waves']=0
        a['imaging waves'] = 'ses-wave'+str(s[0][j])
        df = pd.concat([df,a])

In [21]:
df.head()

,Subject_ID,imaging waves,SWS-waves,ADHD,ChildGender,ID_number,d1_diagadhd_dich,d3_diaagadhd_dich,d5_diagadhd_dich,p0_cpadhdi_raw,p3_cpadhdi_raw,p4_cpadhdi_raw,p5_cpadhdi_raw,d3_ad_inattcri_y,d3_ad_hypcri_y
0,sub-0015,ses-wave3,1,0,1,15,0.0,0,0.0,0,0.0,0.0,0.0,0,0
0,sub-0085,ses-wave3,1,0,0,85,0.0,0,0.0,5,14.0,0.0,1.0,5,0
0,sub-0134,ses-wave3,1,0,1,134,0.0,0,0.0,2,0.0,0.0,0.0,0,0
0,sub-0152,ses-wave3,1,1,0,152,1.0,0,1.0,7,2.0,2.0,3.0,5,3
0,sub-0225,ses-wave3,1,0,1,225,0.0,0,0.0,3,0.0,0.0,0.0,0,0

### df2=main dataframe (dataframe of just subjects with wave3 and SWS)

In [22]:
df2 = df[df['SWS-waves']==1].reset_index(drop=True)

In [46]:
df2

,Subject_ID,imaging waves,SWS-waves,ADHD,ChildGender,ID_number,d1_diagadhd_dich,d3_diaagadhd_dich,d5_diagadhd_dich,p0_cpadhdi_raw,p3_cpadhdi_raw,p4_cpadhdi_raw,p5_cpadhdi_raw,d3_ad_inattcri_y,d3_ad_hypcri_y
0,sub-0015,ses-wave3,1,0,1,15,0.0,0,0.0,0,0.0,0.0,0.0,0,0
1,sub-0085,ses-wave3,1,0,0,85,0.0,0,0.0,5,14.0,0.0,1.0,5,0
2,sub-0134,ses-wave3,1,0,1,134,0.0,0,0.0,2,0.0,0.0,0.0,0,0
3,sub-0152,ses-wave3,1,1,0,152,1.0,0,1.0,7,2.0,2.0,3.0,5,3
4,sub-0225,ses-wave3,1,0,1,225,0.0,0,0.0,3,0.0,0.0,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,sub-7019,ses-wave3,1,0,1,7019,0.0,0,0.0,0,NaN,2.0,0.0,0,0
93,sub-7020,ses-wave3,1,0,0,7020,0.0,0,0.0,4,0.0,1.0,0.0,0,0
94,sub-7069,ses-wave3,1,0,0,7069,0.0,1,NaN,8,6.0,3.0,7.0,7,0
95,sub-7074,ses-wave3,1,0,0,7074,1.0,0,0.0,7,4.0,2.0,4.0,1,0
96,sub-7148,ses-wave3,1,1,1,7148,0.0,1,1.0,12,10.0,12.0,6.0,6,5

In [25]:
df2.to_csv('/media/tara/HD710PRO/NICAP_wave3_subjects/df_wave3_SWS.csv')

### merging df2 with group_bold

In [47]:
group_bold = pd.read_csv('group_bold.tsv', sep='\t')
group_bold

,bids_name,aor,aqi,dummy_trs,dvars_nstd,dvars_std,dvars_vstd,efc,fber,fd_mean,...,summary_bg_stdv,summary_fg_k,summary_fg_mad,summary_fg_mean,summary_fg_median,summary_fg_n,summary_fg_p05,summary_fg_p95,summary_fg_stdv,tsnr
0,sub-0015_ses-wave1_task-rest_bold,0.006006,0.032845,0,41.352940,1.154422,1.039241,0.391380,10046.058594,0.273411,...,20.014797,5.684771,58.764447,465.453400,473.836029,87241.0,334.980011,568.432007,79.931641,32.918119
1,sub-0015_ses-wave3_task-rest_bold,0.000899,0.017761,0,37.355798,1.292336,0.993327,0.395745,13287.402344,0.110859,...,276.155121,4.679665,816.748043,5831.709961,5919.116211,90536.0,4219.392212,7178.098145,1010.982178,47.094205
2,sub-0085_ses-wave2_task-rest_bold,0.000957,0.020011,0,36.674423,1.192335,1.018124,0.370917,16799.005859,0.217484,...,24.435827,5.626375,53.228397,426.326263,436.392029,77206.0,286.313011,521.115021,77.315605,47.315917
3,sub-0085_ses-wave3_task-rest_bold,0.002002,0.032506,0,34.891304,1.129925,0.949688,0.374768,18025.064453,0.248734,...,379.903473,5.457482,799.661921,6260.742188,6397.501953,78492.0,4345.246411,7621.606934,1095.216431,36.709421
4,sub-0086_ses-wave1_task-rest_bold,0.018828,0.043133,0,47.081587,1.171964,1.113701,0.376065,15374.750000,0.472085,...,24.920868,5.548184,66.035093,544.862793,554.296021,82308.0,381.432007,671.166040,95.452019,25.462355
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
325,sub-5927_ses-wave2_task-rest_bold,0.016295,0.049007,0,58.411823,1.204495,1.113746,0.410896,7709.908691,0.441533,...,28.702351,3.746226,82.711404,570.066467,588.230042,96236.0,343.528015,719.369034,117.783417,21.363221
326,sub-5927_ses-wave3_task-rest_bold,0.004772,0.017360,0,34.993247,1.404538,1.067099,0.400165,16834.779297,0.159854,...,363.669464,5.778410,875.974672,6726.939453,6848.048340,95953.0,4960.964941,8206.457617,1131.067139,52.512600
327,sub-5932_ses-wave1_task-rest_bold,0.012188,0.032137,0,37.096906,1.140583,1.036689,0.372592,25736.484375,0.258102,...,28.782850,6.072857,69.634887,563.324646,573.484009,82971.0,418.920013,681.932037,91.656517,33.220779
328,sub-5932_ses-wave2_task-rest_bold,0.002337,0.019782,0,32.374654,1.188742,1.023998,0.378102,18658.525391,0.117529,...,29.373724,5.210026,74.551165,565.936829,577.406006,83656.0,402.286018,694.582016,99.128136,42.730870
329,sub-5932_ses-wave3_task-rest_bold,0.000993,0.019146,0,30.228419,1.207866,0.989414,0.387939,14832.754883,0.168773,...,327.288391,5.387756,748.343470,5814.910156,5920.180176,85580.0,4146.013428,7089.888745,993.942993,48.092603

In [52]:
group_bold["bids_name"] = group_bold["bids_name"].str.split("_")
group_bold.insert(1, "Subject_ID", "0")
group_bold.insert(2, "imaging waves", "0")
for i in range(group_bold.shape[0]):
    group_bold["Subject_ID"][i] = group_bold["bids_name"][i][0]
    group_bold["imaging waves"][i] = group_bold["bids_name"][i][1]

group_bold

AttributeError: Can only use .str accessor with string values!

In [49]:
#df_with_gb = df2.merge(group_bold, on=['Subject_ID' , 'imaging waves'], how='left')
df_with_gb

,Subject_ID,imaging waves,SWS-waves,ADHD,ChildGender,ID_number,d1_diagadhd_dich,d3_diaagadhd_dich,d5_diagadhd_dich,p0_cpadhdi_raw,...,summary_bg_stdv,summary_fg_k,summary_fg_mad,summary_fg_mean,summary_fg_median,summary_fg_n,summary_fg_p05,summary_fg_p95,summary_fg_stdv,tsnr
0,sub-0015,ses-wave3,1,0,1,15,0.0,0,0.0,0,...,276.155121,4.679665,816.748043,5831.709961,5919.116211,90536.0,4219.392212,7178.098145,1010.982178,47.094205
1,sub-0085,ses-wave3,1,0,0,85,0.0,0,0.0,5,...,379.903473,5.457482,799.661921,6260.742188,6397.501953,78492.0,4345.246411,7621.606934,1095.216431,36.709421
2,sub-0134,ses-wave3,1,0,1,134,0.0,0,0.0,2,...,380.924347,5.841348,723.497576,5993.178223,6079.876465,95445.0,4344.366602,7366.400391,1017.725220,42.249399
3,sub-0152,ses-wave3,1,1,0,152,1.0,0,1.0,7,...,292.891693,4.652200,794.561857,5907.045898,6004.064453,82216.0,4164.573120,7249.966309,1022.996765,49.794380
4,sub-0225,ses-wave3,1,0,1,225,0.0,0,0.0,3,...,375.134918,5.629413,715.109435,5791.227051,5912.612305,97526.0,3994.507263,7062.714233,1016.133484,37.062198
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
92,sub-7019,ses-wave3,1,0,1,7019,0.0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
93,sub-7020,ses-wave3,1,0,0,7020,0.0,0,0.0,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,sub-7069,ses-wave3,1,0,0,7069,0.0,1,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,sub-7074,ses-wave3,1,0,0,7074,1.0,0,0.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,sub-7148,ses-wave3,1,1,1,7148,0.0,1,1.0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [31]:
df_with_gb.to_csv('/media/tara/HD710PRO/NICAP_wave3_subjects/dataframe/df_with_gb.csv')

### merging df_with_gb with group_T1w

In [45]:
group_T1w = pd.read_csv('group_T1w.tsv', sep='\t')
group_T1w["bids_name"] = group_T1w["bids_name"].str.split("_")
group_T1w.insert(1, "Subject_ID", "0")
group_T1w.insert(2, "imaging waves", "0")
for i in range(group_T1w.shape[0]):
    group_T1w["Subject_ID"][i] = group_T1w["bids_name"][i][0]
    group_T1w["imaging waves"][i] = group_T1w["bids_name"][i][1]

group_T1w.head()

<ipython-input-45-74dcdf372cdf>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  group_T1w["Subject_ID"][i] = group_T1w["bids_name"][i][0]
<ipython-input-45-74dcdf372cdf>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  group_T1w["imaging waves"][i] = group_T1w["bids_name"][i][1]

,bids_name,Subject_ID,imaging waves,cjv,cnr,efc,fber,fwhm_avg,fwhm_x,fwhm_y,...,summary_wm_mean,summary_wm_median,summary_wm_n,summary_wm_p05,summary_wm_p95,summary_wm_stdv,tpm_overlap_csf,tpm_overlap_gm,tpm_overlap_wm,wm2max
0,"[sub-0015, ses-wave1, T1w]",sub-0015,ses-wave1,0.350552,3.618620,0.643811,372.756683,3.804095,3.932967,3.861448,...,995.921570,1000.015137,301846.0,894.149582,1079.779785,56.016754,0.148441,0.458118,0.486976,0.608414
1,"[sub-0015, ses-wave2, T1w]",sub-0015,ses-wave2,0.303827,4.125028,0.647729,472.670258,3.679930,3.813922,3.749955,...,997.602539,1000.002808,305078.0,916.826511,1068.428021,46.377674,0.152808,0.456861,0.489942,0.635629
2,"[sub-0015, ses-wave3, T1w]",sub-0015,ses-wave3,0.317308,4.126958,0.537321,2532.179932,4.129593,4.204022,4.018734,...,995.745911,1000.011963,315498.0,901.995432,1071.995032,51.632389,0.158227,0.463963,0.496865,0.348531
3,"[sub-0071, ses-wave1, T1w]",sub-0071,ses-wave1,0.368763,3.529735,0.623246,531.137207,3.832442,3.962122,3.860324,...,998.345947,1000.024048,316761.0,909.079651,1081.093994,52.505211,0.138614,0.458274,0.477754,0.606519
4,"[sub-0085, ses-wave2, T1w]",sub-0085,ses-wave2,0.360801,3.248856,0.644359,644.782776,3.562156,3.651478,3.614920,...,997.301331,1000.002930,263420.0,909.174200,1072.202417,51.231632,0.124368,0.418898,0.468719,0.624520

In [33]:
df_with_gb_T1w = df_with_gb.merge(group_T1w, on=['Subject_ID' , 'imaging waves'], how='left')
df_with_gb_T1w

,Subject_ID,imaging waves,SWS-waves,ADHD,ChildGender,ID_number,d1_diagadhd_dich,d3_diaagadhd_dich,d5_diagadhd_dich,p0_cpadhdi_raw,...,summary_wm_mean,summary_wm_median,summary_wm_n,summary_wm_p05,summary_wm_p95,summary_wm_stdv,tpm_overlap_csf,tpm_overlap_gm,tpm_overlap_wm,wm2max
0,sub-0015,ses-wave3,1,0,1,15,0.0,0,0.0,0,...,995.745911,1000.011963,315498.0,901.995432,1071.995032,51.632389,0.158227,0.463963,0.496865,0.348531
1,sub-0085,ses-wave3,1,0,0,85,0.0,0,0.0,5,...,996.437073,1000.006470,258230.0,906.330304,1070.031763,49.267715,0.154975,0.461396,0.488962,0.376340
2,sub-0134,ses-wave3,1,0,1,134,0.0,0,0.0,2,...,999.545776,1000.019165,320010.0,905.605655,1090.527765,56.056854,0.145637,0.456474,0.484460,0.418354
3,sub-0152,ses-wave3,1,1,0,152,1.0,0,1.0,7,...,998.841858,1000.025757,262192.0,918.230725,1074.588312,47.852787,0.169348,0.451484,0.494374,0.378488
4,sub-0225,ses-wave3,1,0,1,225,0.0,0,0.0,3,...,999.412537,1000.026733,304146.0,895.649200,1100.227020,62.269394,0.156407,0.450211,0.478787,0.385430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94,sub-7019,ses-wave3,1,0,1,7019,0.0,0,0.0,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95,sub-7020,ses-wave3,1,0,0,7020,0.0,0,0.0,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,sub-7069,ses-wave3,1,0,0,7069,0.0,1,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,sub-7074,ses-wave3,1,0,0,7074,1.0,0,0.0,7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,sub-7148,ses-wave3,1,1,1,7148,0.0,1,1.0,12,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [34]:
df_with_gb_T1w.to_csv('/media/tara/HD710PRO/NICAP_wave3_subjects/dataframe/df_with_gb_T1w.csv')