In [1]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import os 
import shutil

In [2]:
initial_df = pd.read_csv('dataframe_wave3_subjects.csv')
initial_df.head()

,Subject_ID,imaging waves,SWS-waves,ADHD,ChildGender,ID_number,d1_diagadhd_dich,d3_diaagadhd_dich,d5_diagadhd_dich,p0_cpadhdi_raw,p3_cpadhdi_raw,p4_cpadhdi_raw,p5_cpadhdi_raw,d3_ad_inattcri_y,d3_ad_hypcri_y
0,sub-0015,"1,2,3","4,5",0,1,15,0.0,0,0.0,0,0.0,0.0,0.0,0,0
1,sub-0071,1,4,1,1,71,1.0,1,NaN,14,12.0,12.0,NaN,7,5
2,sub-0085,"2,3","4,5",0,0,85,0.0,0,0.0,5,14.0,0.0,1.0,5,0
3,sub-0086,"1,2,3",NaN,0,1,86,1.0,1,0.0,16,11.0,18.0,NaN,7,5
4,sub-0134,"1,3","4,5",0,1,134,0.0,0,0.0,2,0.0,0.0,0.0,0,0

In [3]:
df = pd.DataFrame(columns=initial_df.columns)
initialdf = initial_df

### spliting imaging waves

In [4]:
initialdf["imaging waves"] = initialdf["imaging waves"].str.split(",")
initialdf["SWS-waves"] = initialdf["SWS-waves"].str.split(",")
initialdf.head()

,Subject_ID,imaging waves,SWS-waves,ADHD,ChildGender,ID_number,d1_diagadhd_dich,d3_diaagadhd_dich,d5_diagadhd_dich,p0_cpadhdi_raw,p3_cpadhdi_raw,p4_cpadhdi_raw,p5_cpadhdi_raw,d3_ad_inattcri_y,d3_ad_hypcri_y
0,sub-0015,"[1, 2, 3]","[4, 5]",0,1,15,0.0,0,0.0,0,0.0,0.0,0.0,0,0
1,sub-0071,[1],[4],1,1,71,1.0,1,NaN,14,12.0,12.0,NaN,7,5
2,sub-0085,"[2, 3]","[4, 5]",0,0,85,0.0,0,0.0,5,14.0,0.0,1.0,5,0
3,sub-0086,"[1, 2, 3]",NaN,0,1,86,1.0,1,0.0,16,11.0,18.0,NaN,7,5
4,sub-0134,"[1, 3]","[4, 5]",0,1,134,0.0,0,0.0,2,0.0,0.0,0.0,0,0

### deleting swsless

In [5]:
initialdf = initialdf.dropna(axis=0, subset=['SWS-waves'])
initialdf.head()

,Subject_ID,imaging waves,SWS-waves,ADHD,ChildGender,ID_number,d1_diagadhd_dich,d3_diaagadhd_dich,d5_diagadhd_dich,p0_cpadhdi_raw,p3_cpadhdi_raw,p4_cpadhdi_raw,p5_cpadhdi_raw,d3_ad_inattcri_y,d3_ad_hypcri_y
0,sub-0015,"[1, 2, 3]","[4, 5]",0,1,15,0.0,0,0.0,0,0.0,0.0,0.0,0,0
1,sub-0071,[1],[4],1,1,71,1.0,1,NaN,14,12.0,12.0,NaN,7,5
2,sub-0085,"[2, 3]","[4, 5]",0,0,85,0.0,0,0.0,5,14.0,0.0,1.0,5,0
4,sub-0134,"[1, 3]","[4, 5]",0,1,134,0.0,0,0.0,2,0.0,0.0,0.0,0,0
5,sub-0152,"[1, 2, 3]","[4, 5]",1,0,152,1.0,0,1.0,7,2.0,2.0,3.0,5,3

In [10]:
index = initialdf['Subject_ID']
main2 = initialdf.set_index('Subject_ID')
index

0      sub-0015
1      sub-0071
2      sub-0085
4      sub-0134
5      sub-0152
         ...
191    sub-7031
192    sub-7069
193    sub-7074
194    sub-7130
195    sub-7148
Name: Subject_ID, Length: 171, dtype: object

In [7]:
main2.to_csv(r'/media/tara/HD710PRO/main2.tsv', index = False)

In [8]:
main2 = pd.read_csv('main2.tsv')
#main2 =

In [9]:
for i in index:
    a = main2.loc[[i]]
    s = a['imaging waves']
    sws = a['SWS-waves'][0]
    a = a.reset_index()
    for j in range(len(s[0])):
        if s[0][j] == '1':
            continue
        if s[0][j] == '2':
            continue
        try:
            if int(sws[0])-2 == int(s[0][j]):
                a['SWS-waves']=1
            elif int(sws[1])-2 == int(s[0][j]):
                a['SWS-waves']=1
            else:
                a['SWS-waves']=0
        except:
            a['SWS-waves']=0
        a['imaging waves'] = 'ses-wave'+str(s[0][j])
        df = pd.concat([df,a])

KeyError: "None of [Index(['sub-0015'], dtype='object')] are in the [index]"

### df=main dataframe

In [ ]:
df.head()

In [ ]:
df2 = df[df['SWS-waves']==1].reset_index(drop=True)
df2.head()

### merging df2 with group_bold

In [ ]:
group_bold = pd.read_csv('group_bold.tsv', sep='\t')
group_bold["bids_name"] = group_bold["bids_name"].str.split("_")
group_bold.insert(1, "Subject_ID", "0")
group_bold.insert(2, "imaging waves", "0")
for i in range(group_bold.shape[0]):
    group_bold["Subject_ID"][i] = group_bold["bids_name"][i][0]
    group_bold["imaging waves"][i] = group_bold["bids_name"][i][1]

group_bold.head()

In [ ]:
#index = group_bold['Subject_ID']
#group_bold = group_bold.reset_index()
group_bold.head()

In [ ]:
for i in index:
    a = group_bold.loc[[i]]
    print(a)